server:
  port: 9090
  servlet:
    context-path: /

spring:
  jackson:
    time-zone: Asia/Shanghai
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/mold?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

mybatis-plus:
  type-aliases-package: com.alee.mold.entity
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted       # 全局逻辑删除字段
      logic-delete-value: 1             # 删除时的值
      logic-not-delete-value: 0         # 未删除时的值